version: 1
language: python
framework: flask
build:
  command: null
run:
  command: gunicorn --bind 0.0.0.0:8000 app:app
ports:
- 8000
env:
- POSTGRES_DB
- POSTGRES_HOST
- POSTGRES_PORT
- POSTGRES_USER
- POSTGRES_PASSWORD
services:
- name: Postgres
  image: postgres:latest
  purpose: Database
notes: Requires a Postgres sidecar
