services:
  app:
    build: .
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-app}:${POSTGRES_PASSWORD:-app}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-app}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-app}
    expose:
      - 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: always

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-app}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app}
      - POSTGRES_DB=${POSTGRES_DB:-app}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data: