"""Open a pull request back to the upstream repo with the generated Dockerfile."""
from dataclasses import dataclass
from pathlib import Path
from urllib.parse import urlparse
import json
import shlex
import shutil
import subprocess
import tempfile

from rich.console import Console


GIT_FILES = ["Dockerfile", "autodock.yaml", "docker-compose.yml"]
BRANCH_NAME = "autodock/add-dockerfile"
PR_TITLE = "Add auto-generated Docker setup"
PR_BODY = (
    "Generated by [Auto-Dock It](https://github.com/) — an agentic LLM tool "
    "that detected the project's stack and produced a Dockerfile (and "
    "compose file where needed) with a self-healing build loop.\n\n"
    "Files added:\n"
    "- `Dockerfile`\n"
    "- `autodock.yaml` (unified config: ports, env vars, run command)\n"
    "- `docker-compose.yml` (if external services were detected)\n\n"
    "The Dockerfile was validated locally: built successfully and the container "
    "responded to an HTTP health check."
)


@dataclass
class PrError(Exception):
    detail: str

    def __str__(self) -> str:
        return self.detail


def _gh(args: list[str], *, cwd: str | None = None, gh_bin: str = "gh") -> subprocess.CompletedProcess:
    return subprocess.run(
        shlex.split(gh_bin) + args, cwd=cwd, capture_output=True, text=True, timeout=60,
    )


def _git(args: list[str], *, cwd: str | None = None) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True, timeout=120,
    )


def _parse_upstream(url: str) -> tuple[str, str]:
    parsed = urlparse(url)
    parts = parsed.path.strip("/").removesuffix(".git").split("/")
    if len(parts) < 2:
        raise PrError(f"cannot parse owner/repo from {url!r}")
    return parts[0], parts[1]


def open_pr(run_dir: Path, *, gh_bin: str = "gh", console: Console | None = None,
            dry_run: bool = False) -> str:
    console = console or Console()
    meta_path = run_dir / "metadata.json"
    if not meta_path.exists():
        raise PrError(f"metadata.json missing in {run_dir}")
    meta = json.loads(meta_path.read_text())
    upstream_url = meta.get("repo_url", "")
    if not upstream_url.startswith("http"):
        raise PrError(f"PR feature requires an http(s) GitHub URL; got {upstream_url!r}")
    owner, repo = _parse_upstream(upstream_url)
    console.print(f"[cyan]Upstream:[/cyan] {owner}/{repo}")

    who = _gh(["api", "user", "--jq", ".login"], gh_bin=gh_bin)
    if who.returncode != 0 or not who.stdout.strip():
        raise PrError("`gh api user` failed. Run `gh auth login` first.")
    me = who.stdout.strip()
    console.print(f"[cyan]Authenticated as:[/cyan] {me}")

    files = [(run_dir / name, name) for name in GIT_FILES if (run_dir / name).exists()]
    if not files:
        raise PrError(f"no files to commit in {run_dir} (expected one of {GIT_FILES})")

    if dry_run:
        console.print("[yellow]--dry-run: skipping fork/clone/push/PR[/yellow]")
        for src, name in files:
            console.print(f"  would commit: {name} ({src.stat().st_size} bytes)")
        return "(dry run)"

    self_owned = (me.lower() == owner.lower())
    if self_owned:
        console.print("[cyan]Upstream is owned by you; pushing branch directly (no fork).[/cyan]")
        clone_url = f"https://github.com/{owner}/{repo}.git"
    else:
        console.print(f"[cyan]Forking {owner}/{repo}...[/cyan]")
        fork = _gh(["repo", "fork", f"{owner}/{repo}", "--clone=false"], gh_bin=gh_bin)
        if fork.returncode != 0 and "already exists" not in fork.stderr:
            raise PrError(f"gh repo fork failed: {fork.stderr.strip()}")
        clone_url = f"https://github.com/{me}/{repo}.git"

    work = Path(tempfile.mkdtemp(prefix="autodock-pr-"))
    try:
        console.print(f"[cyan]Cloning into {work}[/cyan]")
        clone = _git(["clone", "--depth", "1", clone_url, str(work)])
        if clone.returncode != 0:
            raise PrError(f"git clone failed: {clone.stderr.strip()}")

        _git(["checkout", "-b", BRANCH_NAME], cwd=str(work))
        for src, name in files:
            shutil.copyfile(src, work / name)
        _git(["add", *[name for _, name in files]], cwd=str(work))
        _git(["-c", f"user.email={me}@users.noreply.github.com", "-c", f"user.name={me}",
              "commit", "-m", PR_TITLE], cwd=str(work))
        push = _git(["push", "-u", "origin", BRANCH_NAME], cwd=str(work))
        if push.returncode != 0:
            raise PrError(f"git push failed: {push.stderr.strip()}")

        console.print(f"[cyan]Opening PR against {owner}/{repo}...[/cyan]")
        head_ref = BRANCH_NAME if self_owned else f"{me}:{BRANCH_NAME}"
        pr = _gh([
            "pr", "create",
            "--repo", f"{owner}/{repo}",
            "--head", head_ref,
            "--title", PR_TITLE,
            "--body", PR_BODY,
        ], gh_bin=gh_bin)
        if pr.returncode != 0:
            raise PrError(f"gh pr create failed: {pr.stderr.strip()}")
        url = pr.stdout.strip().splitlines()[-1]
        console.print(f"[green]PR opened:[/green] {url}")
        return url
    finally:
        shutil.rmtree(work, ignore_errors=True)
